version: '1'
services:
  web:
    build: .
    command: npm app.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
        - data-volume:/data/db
volumes:
  data-volume: